
  CREATE TABLE "SYSTEM"."BOARD" 
   (	"NUM" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"WRITER" VARCHAR2(20 CHAR), 
	"EMAIL" VARCHAR2(50 CHAR), 
	"SUBJECT" VARCHAR2(50 CHAR), 
	"PASSWORD" VARCHAR2(10 CHAR), 
	"REG_DATE" DATE, 
	"REF" NUMBER, 
	"RE_STEP" NUMBER, 
	"RE_LEVEL" NUMBER, 
	"READCOUNT" NUMBER, 
	"CONTENT" VARCHAR2(500 CHAR), 
	 CONSTRAINT "BOARD_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;